/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarHistory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fengpeng
 */
public class SearchCarsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form searchCarsJPanel
     */
    private CarHistory carHistory;
    private JPanel UserProcessContainer;
    private List<Car> showCarsList;
    public SearchCarsJPanel() {
    }

    SearchCarsJPanel(CarHistory carHistory, JPanel UserProcessContainer) {
        initComponents();
        this.carHistory = carHistory;
        this.UserProcessContainer = UserProcessContainer;
        showCarsList = new ArrayList<Car>();
    }
    
    private void populate() {
        DefaultTableModel dtm=(DefaultTableModel) tableSearchedCars.getModel();
        dtm.setRowCount(0);
        for (Car car : showCarsList) {
            Object[] row = new Object[11];
                row[0] = car.getSerialNumber();
                row[1] = car.getBrand();
                row[2] = car.getModelNumber();
                row[3] = car.getManufatureYear();
                row[4] = car.getMinSeats();
                row[5] = car.getMaxSeats();
                row[6] = car.getCity();
                row[7] = car.isIsAvailable();
                row[8] = car.isExpired();
                row[9] = car.getManfaturer();
                row[10] = car.getLastUpdated();
                dtm.addRow(row);
        }
    }
    
    private void clearText(String check) {
        DefaultTableModel dtm=(DefaultTableModel) tableManufaturer.getModel();
        switch(check) {
            case "brand": 
                texCity.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");               
                dtm.setRowCount(0);
                break;
            case "ManuYear": 
                texBrand.setText("");
                texCity.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");
                dtm.setRowCount(0);
                break;
            case "SerialNumber": 
                texBrand.setText("");
                texCity.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                dtm.setRowCount(0);
                break;
            case "ModelNumber": 
                texBrand.setText("");
                texCity.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texSerialNumber.setText("");
                dtm.setRowCount(0);
                break;
            case "City": 
                texBrand.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");
                dtm.setRowCount(0);
                break;
            case "Seats": 
                texBrand.setText("");
                texCity.setText("");
                texManuYear.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");
                dtm.setRowCount(0);
                break;
            case "Manufaturers": 
                texBrand.setText("");
                texCity.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");
                break;
            case "All": 
                texBrand.setText("");
                texCity.setText("");
                texManuYear.setText("");
                texMaxSeats.setText("");
                texMinSeats.setText("");
                texModelNumber.setText("");
                texSerialNumber.setText("");
                dtm.setRowCount(0);
                break;
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSearchedCars = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableManufaturer = new javax.swing.JTable();
        btnAllManufaturers = new javax.swing.JButton();
        boxConditions = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        texBrand = new javax.swing.JTextField();
        btnSeats = new javax.swing.JButton();
        texMinSeats = new javax.swing.JTextField();
        texCity = new javax.swing.JTextField();
        texMaxSeats = new javax.swing.JTextField();
        texManuYear = new javax.swing.JTextField();
        texSerialNumber = new javax.swing.JTextField();
        texModelNumber = new javax.swing.JTextField();
        btnBrand = new javax.swing.JButton();
        btnSerialNumber = new javax.swing.JButton();
        btnManuYear = new javax.swing.JButton();
        btnModelNumber = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCity = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tableSearchedCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        tableSearchedCars.setForeground(new java.awt.Color(0, 102, 102));
        tableSearchedCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial NO.", "Brand", "Model NO.", "Manu Year", "Min_seat", "Max_seat", "City", "Available", "Expired", "Manufacturer", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSearchedCars);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search By Conditions");

        tableManufaturer.setForeground(new java.awt.Color(0, 153, 153));
        tableManufaturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableManufaturer);

        btnAllManufaturers.setText("All Manufaturers");
        btnAllManufaturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllManufaturersActionPerformed(evt);
            }
        });

        boxConditions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Cars", "All Available Car", "All Non-available Cars", "Expired Cars" }));
        boxConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxConditionsActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        texBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texBrandActionPerformed(evt);
            }
        });

        btnSeats.setText("Seats Range");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        btnBrand.setText("Brand");
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnSerialNumber.setText("Serial NO.");
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        btnManuYear.setText("Manu. Year");
        btnManuYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuYearActionPerformed(evt);
            }
        });

        btnModelNumber.setText("Model NO.");
        btnModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNumberActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");

        btnCity.setText("City");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });

        btnDetails.setText("View Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(texCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(texMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(boxConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnAllManufaturers, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDetails)
                                .addGap(10, 10, 10)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAllManufaturers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxConditionsActionPerformed

    private void texBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texBrandActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        String brand = texBrand.getText();
        if (!brand.equals("")) {
            showCarsList = carHistory.searchCarByBrand(brand);
            populate();
            clearText("brand");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in the brand", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnManuYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuYearActionPerformed
        // TODO add your handling code here:
        try {
            int manuYear = Integer.parseInt(texManuYear.getText());
            showCarsList = carHistory.searchCarByManuYear(manuYear);
            populate();
            clearText("ManuYear");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please input validate year", "warning",JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_btnManuYearActionPerformed

    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
        try {
            int serialNumber = Integer.parseInt(texSerialNumber.getText());
            showCarsList = carHistory.searchCarBySerialNumber(serialNumber);
            populate();
            clearText("SerialNumber");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please input validate serial number", "warning",JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void btnModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNumberActionPerformed
        // TODO add your handling code here:
        String modelNumber = texModelNumber.getText();
        if (!modelNumber.equals("")) {
            showCarsList = carHistory.searchCarByModelNumber(modelNumber);
            populate();
            clearText("ModelNumber");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in the model number", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnModelNumberActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
        String city = texCity.getText();
        if (!city.equals("")) {
            showCarsList = carHistory.searchCarByCity(city);
            populate();
            clearText("City");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in the city", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
        try {
            int minSeats = Integer.parseInt(texMinSeats.getText());
            int maxSeats = Integer.parseInt(texMaxSeats.getText());
            showCarsList = carHistory.searchCarBySeats(minSeats, maxSeats);
            populate();
            clearText("Seats");           
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill in the min seats and max seats", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int selected = boxConditions.getSelectedIndex();
        switch(selected) {
            case 0:
                showCarsList = carHistory.getCarList();
                populate();
                clearText("All");
                break;
            case 1:
                showCarsList = carHistory.getAvailableCars();
                populate();
                clearText("All");
                break;
            case 2:
                showCarsList = carHistory.getNonAvailableCars();
                populate();
                clearText("All");
                break;
            case 3:
                showCarsList = carHistory.ExpiredCars();
                populate();
                clearText("All");
                break;
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllManufaturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllManufaturersActionPerformed
        // TODO add your handling code here:
        List<String> manufaturers = new ArrayList<>();
        for (Car car : carHistory.getCarList()) {
            if (!manufaturers.contains(car.getManfaturer())) {
                manufaturers.add(car.getManfaturer());
            } 
        }
        
        DefaultTableModel dtm=(DefaultTableModel) tableManufaturer.getModel();
        dtm.setRowCount(0);
        for (String str : manufaturers) {
            Object[] obj = new Object[1];
            obj[0] = str;
            dtm.addRow(obj);
        }
        clearText("Manufaturers");
        
        
    }//GEN-LAST:event_btnAllManufaturersActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedAvailRow = tableSearchedCars.getSelectedRow();
        
        if (selectedAvailRow >= 0) {
            Car curCar = new Car();
            for (Car car : carHistory.getCarList()) {
                if (car.getSerialNumber() == (int)tableSearchedCars.getValueAt(selectedAvailRow, 0)) {
                    curCar = car;
                    break;
                }
            }
            ViewCarJPanel viewCarJPanel = new ViewCarJPanel(curCar, UserProcessContainer);
            UserProcessContainer.add("ViewCarJPanel", viewCarJPanel);
            CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
            layout.next(UserProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "warning",JOptionPane.WARNING_MESSAGE);  
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxConditions;
    private javax.swing.JButton btnAllManufaturers;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnManuYear;
    private javax.swing.JButton btnModelNumber;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableManufaturer;
    private javax.swing.JTable tableSearchedCars;
    private javax.swing.JTextField texBrand;
    private javax.swing.JTextField texCity;
    private javax.swing.JTextField texManuYear;
    private javax.swing.JTextField texMaxSeats;
    private javax.swing.JTextField texMinSeats;
    private javax.swing.JTextField texModelNumber;
    private javax.swing.JTextField texSerialNumber;
    // End of variables declaration//GEN-END:variables
}
