/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarHistory;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fengpeng
 */
public class ViewCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCarJPanel
     */
    private Car car;
    private JPanel UserProcessContainer;
    private CarHistory carHistory;
    public ViewCarJPanel() {
        
    }

   
    ViewCarJPanel(Car car, JPanel UserProcessContainer) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.car=car;
        populate(); 
        carHistory = new CarHistory();
    }
    
    private void populate() {
        texCity.setText(car.getCity());
        texBrand.setText(car.getBrand());
        texManuYear.setText(String.valueOf(car.getManufatureYear()));
        texMinSeats.setText(String.valueOf(car.getMinSeats()));
        texMaxSeats.setText(String.valueOf(car.getMaxSeats()));
        texManfaturer.setText(car.getManfaturer());
        texSerialNumber.setText(String.valueOf(car.getSerialNumber()));
        texModelNumber.setText(car.getModelNumber());
        radioAvailableYes.setSelected(car.isIsAvailable());
        radioAvailableNo.setSelected(!car.isIsAvailable());
        radioMantenanceNo.setSelected(!car.isExpired());
        radioMantenanceYes.setSelected(car.isExpired());
        texLastUpdated.setText(car.getLastUpdated());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMantenace = new javax.swing.ButtonGroup();
        groupAvailable = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texMaxSeats = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        texCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        texManuYear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        texMinSeats = new javax.swing.JTextField();
        radioMantenanceYes = new javax.swing.JRadioButton();
        texBrand = new javax.swing.JTextField();
        radioMantenanceNo = new javax.swing.JRadioButton();
        texModelNumber = new javax.swing.JTextField();
        radioAvailableYes = new javax.swing.JRadioButton();
        texManfaturer = new javax.swing.JTextField();
        radioAvailableNo = new javax.swing.JRadioButton();
        texSerialNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        texLastUpdated = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View");

        jLabel2.setText("Expired: ");

        jLabel3.setText("City: ");

        jLabel4.setText("Serial Number:");

        jLabel5.setText("Model Number:");

        jLabel6.setText("Brand: ");

        jLabel7.setText("Manfaturer:");

        jLabel8.setText("Min Seats: ");

        texMaxSeats.setEnabled(false);

        jLabel9.setText("Manu Year: ");

        texCity.setEnabled(false);
        texCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texCityActionPerformed(evt);
            }
        });

        jLabel10.setText("Max Seats: ");

        texManuYear.setEnabled(false);

        jLabel11.setText("Available: ");

        texMinSeats.setEnabled(false);

        groupMantenace.add(radioMantenanceYes);
        radioMantenanceYes.setText("Yes");
        radioMantenanceYes.setEnabled(false);

        texBrand.setEnabled(false);

        groupMantenace.add(radioMantenanceNo);
        radioMantenanceNo.setText("No");
        radioMantenanceNo.setEnabled(false);

        texModelNumber.setEnabled(false);

        groupAvailable.add(radioAvailableYes);
        radioAvailableYes.setText("Yes");
        radioAvailableYes.setEnabled(false);

        texManfaturer.setEnabled(false);

        groupAvailable.add(radioAvailableNo);
        radioAvailableNo.setText("No");
        radioAvailableNo.setEnabled(false);

        texSerialNumber.setEnabled(false);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("LastUpdate:");

        texLastUpdated.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBack)
                        .addGap(454, 454, 454)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texCity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(264, 264, 264)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texManfaturer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioMantenanceYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioMantenanceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioAvailableYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(texLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texManfaturer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioMantenanceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioMantenanceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioAvailableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texCity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(texMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void texCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texCityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_texCityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        texBrand.setEnabled(true);
        texCity.setEnabled(true);
        texManfaturer.setEnabled(true);
        texManuYear.setEnabled(true);
        texMaxSeats.setEnabled(true);
        texMinSeats.setEnabled(true);
        texModelNumber.setEnabled(true);
        texSerialNumber.setEnabled(true);
        radioAvailableNo.setEnabled(true);
        radioAvailableYes.setEnabled(true);
        radioMantenanceNo.setEnabled(true);
        radioMantenanceYes.setEnabled(true);
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Car oldCar = car; 
        try {
            if (texCity.getText().equals("") || texBrand.getText().equals("") || texManuYear.getText().equals("") || texMinSeats.getText().equals("") || texMaxSeats.getText().equals("")
                    || texManfaturer.getText().equals("") || texSerialNumber.getText().equals("") || texModelNumber.getText().equals("") || groupMantenace.getSelection() == null || groupAvailable.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Please fill in all information.", "warning",JOptionPane.WARNING_MESSAGE);
            } else {
                
                if (Integer.parseInt(texSerialNumber.getText()) != oldCar.getSerialNumber() && carHistory.getSerialNumberList().contains(Integer.parseInt(texSerialNumber.getText()))) {
                    carHistory.deleteCar(car);
                    JOptionPane.showMessageDialog(null, "Serial Number should be unique", "warning", JOptionPane.WARNING_MESSAGE);
                        
                } else if (Integer.parseInt(texMinSeats.getText()) > Integer.parseInt(texMaxSeats.getText())) {
                    carHistory.deleteCar(car);
                    JOptionPane.showMessageDialog(null, "Wrong min Seats or max Seats", "warning",JOptionPane.WARNING_MESSAGE);
                }else {
                    car.setSerialNumber(Integer.parseInt(texSerialNumber.getText()));
                    car.setCity(texCity.getText());
                    car.setBrand(texBrand.getText());
                    car.setManufatureYear(Integer.parseInt(texManuYear.getText()));
                    car.setMinSeats(Integer.parseInt(texMinSeats.getText()));
                    car.setMaxSeats(Integer.parseInt(texMaxSeats.getText()));
                    car.setManfaturer(texManfaturer.getText());
                    
                    car.setModelNumber(texModelNumber.getText());
                    Enumeration<AbstractButton> radioMantenace = groupMantenace.getElements();
                    String maintenance = "";
                    while (radioMantenace.hasMoreElements()) {              
                        AbstractButton btn = radioMantenace.nextElement();
                        if (btn.isSelected()) {
                            maintenance = btn.getText();
                            break;
                        }

                    }
                    car.setExpired(maintenance.equals("Yes") ? true : false);

                    Enumeration<AbstractButton> radioAvailable = groupAvailable.getElements();
                    String available = "";
                    while (radioAvailable.hasMoreElements()) {              
                        AbstractButton btn = radioAvailable.nextElement();
                        if (btn.isSelected()) {
                            available = btn.getText();
                            break;
                        }
                    }
                    car.setIsAvailable(available.equals("Yes") ? true : false);
                    car.setLastUpdated(new Date());
                    texLastUpdated.setText(car.getLastUpdated());

                    JOptionPane.showMessageDialog(null, "Account successfully created!");
                    texBrand.setEnabled(false);
                    texCity.setEnabled(false);
                    texManfaturer.setEnabled(false);
                    texManuYear.setEnabled(false);
                    texMaxSeats.setEnabled(false);
                    texMinSeats.setEnabled(false);
                    texModelNumber.setEnabled(false);
                    texSerialNumber.setEnabled(false);
                    radioAvailableNo.setEnabled(false);
                    radioAvailableYes.setEnabled(false);
                    radioMantenanceNo.setEnabled(false);
                    radioMantenanceYes.setEnabled(false);
                }
                
            }
            
        } catch(Exception e) {
            car = oldCar;
            JOptionPane.showMessageDialog(null, "Please fill in the validate information", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup groupAvailable;
    private javax.swing.ButtonGroup groupMantenace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioAvailableNo;
    private javax.swing.JRadioButton radioAvailableYes;
    private javax.swing.JRadioButton radioMantenanceNo;
    private javax.swing.JRadioButton radioMantenanceYes;
    private javax.swing.JTextField texBrand;
    private javax.swing.JTextField texCity;
    private javax.swing.JTextField texLastUpdated;
    private javax.swing.JTextField texManfaturer;
    private javax.swing.JTextField texManuYear;
    private javax.swing.JTextField texMaxSeats;
    private javax.swing.JTextField texMinSeats;
    private javax.swing.JTextField texModelNumber;
    private javax.swing.JTextField texSerialNumber;
    // End of variables declaration//GEN-END:variables
}
