/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Order;
import Business.Restaurant.OrderItem;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.NewCustomerJPanel;

/**
 *
 * @author raunak
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private UserAccount account;
    private EcoSystem ecosystem;
    private Customer customer;
    private Restaurant selectedRes;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
      
        this.account = account;
        this.customer = ecosystem.getCustomerDirectory().searchCustomerByUsername(account.getUsername());
        
        this.ecosystem = ecosystem;
        
    }
    
    public void populateTableRes(Restaurant searchedRes) {
        DefaultTableModel dtm = (DefaultTableModel) tableRes.getModel();
        dtm.setRowCount(0);
        
        Object[] row = new Object[4];
        row[0] = searchedRes.getResName();
        row[1] = searchedRes.getResManager();
        row[2] = searchedRes.getAddress();
        row[3] = searchedRes.getPhone();
        dtm.addRow(row);
    }
    
    public void populateAllRes() {
        DefaultTableModel dtm = (DefaultTableModel) tableRes.getModel();
        dtm.setRowCount(0);
        
        for (Restaurant res : ecosystem.getRestaurantDirectory().getRestaurantList()) {
            Object[] row = new Object[4];
            row[0] = res.getResName();
            row[1] = res.getResManager();
            row[2] = res.getAddress();
            row[3] = res.getPhone();
            dtm.addRow(row);
        }
    }
    
    public void populateMenu(Restaurant selectedRes) {
        DefaultTableModel dtm = (DefaultTableModel) tableMenu.getModel();
        dtm.setRowCount(0);
        
        for (MenuItem item : selectedRes.getMenus()) {
            Object[] row = new Object[3];
            row[0] = item.getDishName();
            row[1] = item.getDescription();
            row[2] = item.getPrice();
            dtm.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnListAllRes = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnViewMenu = new javax.swing.JButton();
        btnOrderHis = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Work Area");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Restaurant: ");

        tableRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Restaurant", "Manager", "Address", "Phone"
            }
        ));
        jScrollPane2.setViewportView(tableRes);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restaurant");

        btnListAllRes.setText("List all Restaurants");
        btnListAllRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllResActionPerformed(evt);
            }
        });

        btnPlaceOrder.setText("Place an Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Description", "Price"
            }
        ));
        jScrollPane3.setViewportView(tableMenu);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menu");

        btnViewMenu.setText("View Menu");
        btnViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMenuActionPerformed(evt);
            }
        });

        btnOrderHis.setText("Ordered History");
        btnOrderHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHisActionPerformed(evt);
            }
        });

        jLabel5.setText("Number: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnPlaceOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderHis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearch)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(btnListAllRes))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewMenu)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAllRes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderHis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String resName = txtRes.getText();
        if (resName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter restaurant name.");
        } else {
            Restaurant searchedRes = ecosystem.getRestaurantDirectory().searchResByName(resName);
            if (searchedRes == null) {
                JOptionPane.showMessageDialog(null, "No searched result");
                return;
            } else {
                populateTableRes(searchedRes);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnListAllResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllResActionPerformed
        // TODO add your handling code here:
        populateAllRes();
    }//GEN-LAST:event_btnListAllResActionPerformed

    private void btnViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMenuActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRes.getSelectedRow();
        
        if (selectedRow >= 0) {
            String resName = (String)tableRes.getValueAt(selectedRow, 0);
            selectedRes = ecosystem.getRestaurantDirectory().searchResByName(resName);
            populateMenu(selectedRes);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnViewMenuActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tableMenu.getSelectedRow();
            int number = Integer.parseInt(txtNumber.getText());
            if (selectedRow >= 0) {
                String itemName = (String)tableMenu.getValueAt(selectedRow, 0);
               
                MenuItem selectItem = selectedRes.searchItemByName(itemName);
                OrderItem orderItem = new OrderItem(selectItem, number);
                String orderId = selectedRes.getResName() + " " + selectedRes.getOrders().size() + 1;
                Order newOrder = new Order(orderId, customer.getUsername(), selectedRes.getResName(), orderItem);
                customer.getOrders().add(newOrder);
                selectedRes.getOrders().add(newOrder);
                JOptionPane.showMessageDialog(null, "Place order successfully.");

            } else {
                JOptionPane.showMessageDialog(null, "Please select a row.");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Number must be integer");
        }
        
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnOrderHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHisActionPerformed
        // TODO add your handling code here:
        OrderedHistoryJPanel orderedHisJPanel = new OrderedHistoryJPanel(userProcessContainer, ecosystem, customer);
        userProcessContainer.add("OrderedHistoryJPanel",orderedHisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrderHisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListAllRes;
    private javax.swing.JButton btnOrderHis;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTable tableRes;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtRes;
    // End of variables declaration//GEN-END:variables
}
